CREATE TABLE DA.UKUPNIBODOVI (
    INDEKS  INTEGER     NOT NULL,
    IME     VARCHAR(25) NOT NULL,
    PREZIME VARCHAR(25) NOT NULL,
    ESPB    INTEGER     NOT NULL,
    PRIMARY KEY(INDEKS),
    FOREIGN KEY(INDEKS) REFERENCES DA.DOSIJE    
);

INSERT      INTO DA.UKUPNIBODOVI
SELECT      D.INDEKS, 
            IME, 
            PREZIME, 
            SUM(CASE 
                WHEN OCENA > 5 AND STATUS = 'o' THEN P.ESPB 
                ELSE 0 
                END) UKUPNO_BODOVA
FROM        DA.DOSIJE D JOIN
            DA.ISPIT I ON D.INDEKS = I.INDEKS JOIN
            DA.PREDMET P ON I.IDPREDMETA = P.ID
GROUP BY    D.INDEKS, IME, PREZIME
ORDER BY    UKUPNO_BODOVA DESC;