# -*- coding: utf-8 -*-
"""04_sklearn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IXrX532Yc4xRy842tVhdqoKMiEcZ3JL_
"""

from sklearn import linear_model
import pandas as pd
from matplotlib import pyplot as plt

data = pd.read_csv('advertising.csv')
data.head()

tv = data['TV']
radio = data['Radio']
newspaper = data['Newspaper']
sales = data['Sales']

plt.scatter(tv, sales)
plt.show()

plt.scatter(radio, sales)
plt.show()

plt.scatter(newspaper, sales)
plt.show()

model = linear_model.LinearRegression()

from sklearn import model_selection

X = data[['TV', 'Radio', 'Newspaper']]

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, sales, test_size=0.3, random_state=17)

model.fit(X_train, y_train)

# slobodan clan beta_0
model.intercept_

# preostali koeficijenti (beta1, beta2...)
model.coef_

from sklearn import metrics

y_pred = model.predict(X_test)

# srednje kvadratna greska
mse = metrics.mean_squared_error(y_test, y_pred)
mse
mae = metrics.mean_absolute_error(y_test, y_pred)
mae
r2 = metrics.r2_score(y_test, y_pred)
r2