# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prozor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(170, 170, 170)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(230, 10, 131, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rbDefault = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbDefault.setStyleSheet("background-color: rgb(255, 0, 0)")
        self.rbDefault.setObjectName("rbDefault")
        self.verticalLayout.addWidget(self.rbDefault)
        self.rbCustom = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbCustom.setStyleSheet("background-color: rgb(255, 0, 0)")
        self.rbCustom.setObjectName("rbCustom")
        self.verticalLayout.addWidget(self.rbCustom)
        self.leDefault = QtWidgets.QLineEdit(self.centralwidget)
        self.leDefault.setGeometry(QtCore.QRect(370, 30, 311, 31))
        self.leDefault.setStyleSheet("background-color: rgb(85, 170, 0)")
        self.leDefault.setInputMask("")
        self.leDefault.setObjectName("leDefault")
        self.leCustom = QtWidgets.QLineEdit(self.centralwidget)
        self.leCustom.setGeometry(QtCore.QRect(370, 80, 311, 31))
        self.leCustom.setStyleSheet("background-color: rgb(85, 170, 0)")
        self.leCustom.setInputMask("")
        self.leCustom.setText("")
        self.leCustom.setObjectName("leCustom")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(250, 150, 461, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.lblProgress = QtWidgets.QLabel(self.centralwidget)
        self.lblProgress.setGeometry(QtCore.QRect(260, 180, 351, 61))
        self.lblProgress.setStyleSheet("font: 75 18pt \"Ubuntu\";\n"
"text-decoration: line-through;\n"
"font-weight: bold;")
        self.lblProgress.setObjectName("lblProgress")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 320, 186, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbRSA = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.cbRSA.setObjectName("cbRSA")
        self.verticalLayout_2.addWidget(self.cbRSA)
        self.cbTTY = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.cbTTY.setObjectName("cbTTY")
        self.verticalLayout_2.addWidget(self.cbTTY)
        self.cbTCP = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.cbTCP.setObjectName("cbTCP")
        self.verticalLayout_2.addWidget(self.cbTCP)
        self.cbP2P = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.cbP2P.setObjectName("cbP2P")
        self.verticalLayout_2.addWidget(self.cbP2P)
        self.cbTS = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.cbTS.setObjectName("cbTS")
        self.verticalLayout_2.addWidget(self.cbTS)
        self.dialVPS = QtWidgets.QDial(self.centralwidget)
        self.dialVPS.setGeometry(QtCore.QRect(250, 290, 151, 151))
        self.dialVPS.setObjectName("dialVPS")
        self.lblVPS = QtWidgets.QLabel(self.centralwidget)
        self.lblVPS.setGeometry(QtCore.QRect(260, 460, 131, 17))
        self.lblVPS.setObjectName("lblVPS")
        self.lblIDRS = QtWidgets.QLabel(self.centralwidget)
        self.lblIDRS.setGeometry(QtCore.QRect(440, 460, 151, 17))
        self.lblIDRS.setObjectName("lblIDRS")
        self.dialIDRS = QtWidgets.QDial(self.centralwidget)
        self.dialIDRS.setGeometry(QtCore.QRect(430, 280, 151, 171))
        self.dialIDRS.setObjectName("dialIDRS")
        self.vsD5 = QtWidgets.QSlider(self.centralwidget)
        self.vsD5.setGeometry(QtCore.QRect(640, 290, 20, 171))
        self.vsD5.setOrientation(QtCore.Qt.Vertical)
        self.vsD5.setObjectName("vsD5")
        self.lblD5 = QtWidgets.QLabel(self.centralwidget)
        self.lblD5.setGeometry(QtCore.QRect(640, 470, 31, 17))
        self.lblD5.setObjectName("lblD5")
        self.lblS45 = QtWidgets.QLabel(self.centralwidget)
        self.lblS45.setGeometry(QtCore.QRect(690, 470, 31, 17))
        self.lblS45.setObjectName("lblS45")
        self.vsS45 = QtWidgets.QSlider(self.centralwidget)
        self.vsS45.setGeometry(QtCore.QRect(690, 290, 20, 171))
        self.vsS45.setOrientation(QtCore.Qt.Vertical)
        self.vsS45.setObjectName("vsS45")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 160, 121))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bStart = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.bStart.setStyleSheet("background-color: rgb(0, 170, 0)")
        self.bStart.setObjectName("bStart")
        self.verticalLayout_3.addWidget(self.bStart)
        self.bStop = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.bStop.setStyleSheet("background-color: rgb(255, 27, 11)")
        self.bStop.setObjectName("bStop")
        self.verticalLayout_3.addWidget(self.bStop)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(193, 0, 20, 311))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(80, 260, 641, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rbDefault.setText(_translate("MainWindow", "Default hack:"))
        self.rbCustom.setText(_translate("MainWindow", "Custom hack:"))
        self.leDefault.setText(_translate("MainWindow", "www.matf.bg.ac.rs"))
        self.lblProgress.setText(_translate("MainWindow", "Waiting on port  5546/9982/2"))
        self.cbRSA.setText(_translate("MainWindow", "RSA Transport Pipeline"))
        self.cbTTY.setText(_translate("MainWindow", "TTY Password Locker"))
        self.cbTCP.setText(_translate("MainWindow", "Dead TCP Loader"))
        self.cbP2P.setText(_translate("MainWindow", "Peer to Peer Unlocker"))
        self.cbTS.setText(_translate("MainWindow", "Transport Switcher"))
        self.lblVPS.setText(_translate("MainWindow", "Tune attack VPS"))
        self.lblIDRS.setText(_translate("MainWindow", "Tune defense IDRS"))
        self.lblD5.setText(_translate("MainWindow", "D5"))
        self.lblS45.setText(_translate("MainWindow", "S45"))
        self.bStart.setText(_translate("MainWindow", "Start Engine"))
        self.bStop.setText(_translate("MainWindow", "Stop Engine"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

