CREATE TABLE DA.DRZAVA (
    IDDRZAVE INTEGER NOT NULL PRIMARY KEY,
    NAZIV VARCHAR(50) NOT NULL
);

CREATE TABLE DA.EKSKURZIJA (
    INDEKS INTEGER NOT NULL,
    IDDRZAVE INTEGER NOT NULL,
    TRENUTAKPRIJAVE TIMESTAMP NOT NULL,
    PRIMARY KEY (INDEKS),
    FOREIGN KEY (INDEKS) REFERENCES DA.DOSIJE,
    FOREIGN KEY (IDDRZAVE) REFERENCES DA.DRZAVA
);

INSERT  INTO DA.DRZAVA
VALUES  (1, 'Spanija'),
        (2, 'Italija'),
        (3, 'Grcka'),
        (4, 'Nemacka'),
        (5, 'Rusija'),
        (6, 'Francuska');
