DROP    TABLE DA.STATISTIKAPOLAGANJA;

CREATE  TABLE DA.STATISTIKAPOLAGANJA (
    SKGODINA    SMALLINT NOT NULL,
    OZNAKAROKA  VARCHAR(20) NOT NULL,
    IDPREDMETA  INTEGER NOT NULL,
    USPESNOST   DOUBLE,
    PRIMARY KEY (SKGODINA, OZNAKAROKA, IDPREDMETA),
    FOREIGN KEY (SKGODINA, OZNAKAROKA) 
                REFERENCES DA.ISPITNIROK,
    FOREIGN KEY (IDPREDMETA)
                REFERENCES DA.PREDMET
);
