-- 1.
--select d.indeks, ime, prezime, p.sifra, char(ocena)
--from dosije d left join ispit i
--		on d.indeks = i.indeks
--	join predmet p
--		on p.id_predmeta = i.id_predmeta
--where year(datum_rodjenja) is not null
--	and datum_ispita is not null
--	
--union
--	
--select d.indeks, ime, prezime, p.sifra, 
--		'Nepoznati godina rodjenja i datum ispita'
--from dosije d left join ispit i
--		on d.indeks = i.indeks
--	join predmet p
--		on p.id_predmeta = i.id_predmeta
--where year(datum_rodjenja) is null
--	and datum_ispita is null
--	
--union 
--
--select d.indeks, ime, prezime, p.sifra, char(-1*ocena)
--from dosije d left join ispit i
--		on d.indeks = i.indeks
--	join predmet p
--		on p.id_predmeta = i.id_predmeta
--where (year(datum_rodjenja) is not null
--	and datum_ispita is null) 
--	or 
--	(year(datum_rodjenja) is null
--	and datum_ispita is not null)

-- 2. 
--select bodovi "Broj bodova", listagg(naziv, ', ') "Predmeti"
--from predmet
--group by bodovi
--order by bodovi desc

-- 3.
--select d.indeks, ime, prezime, naziv
--from dosije d join ispit i
--		on i.indeks = d.indeks
--	    and ocena > 5
--	 join predmet p
--	  	on p.id_predmeta = i.id_predmeta
--where dayname(datum_ispita) = dayname(last_day('1.12.' || char(year(datum_rodjenja))))

-- 4. 
--select ime, prezime
--from dosije d join ispit i
--	on i.indeks = d.indeks
--group by ime, prezime
--having avg(ocena*1.0) >= (select avg(ocena*1.0)+stddev(ocena)
--					      from ispit)
--					      
--union 
--
--select ime, prezime
--from dosije d join ispit i
--	on i.indeks = d.indeks
--group by ime, prezime
--having avg(ocena*1.0) <= (select avg(ocena*1.0)-stddev(ocena)
--					      from ispit)

-- 5. 
--select ime, prezime, 
--	   year(current date)-year(datum_rodjenja) "Protekle godine",
--	   month(current date)-month(datum_rodjenja) "Protekli meseci",
--	   days(current date)-days(datum_rodjenja) "Protekli dani"
--from dosije

-- 6.
--select count(d.indeks), avg(ocena*1.0) prosek, stddev(ocena)
--from dosije d left join ispit i
--		on d.indeks = i.indeks
--		and ocena > 5
--group by d.mesto_rodjenja

-- 7.
--select replace(ime, 'ra', 'arny'),
--   	   replace(prezime, 'ra', 'arny')
--from dosije

-- 8. 
--select d.indeks, 
--	case
--		when d.indeks not in (select indeks from ispit) then 'Nije polagao nijedan ispit'
--		when avg(ocena*1.0) is null then -1
--		else char(avg(ocena*1.0))
--	end
--from dosije d join ispit i
--	on d.indeks = i.indeks
--where dayname(datum_rodjenja) = 'Friday'
--	and day(datum_rodjenja) = 13
--	and ocena > 5
--group by d.indeks, datum_rodjenja

--- 47.---------


